---
- name: role testing 
  hosts: localhost 

  vars: 
     my_version: 1.0

  vars_files: 
    - vars/included_vars.yml 

  tasks: 
    - name: display version 
      debug: 
        msg: "My Version: {{ my_version }} , version from file {{ version }}  "

    - name: say hi 
      debug: 
        msg: "HI from Main program"

    - include: tasks/included_tasks.yml 
      vars:
          name: "Mahesh"
          complex_msg: "very tricky situation"

    - name: verify file exists 
      stat: 
        path: /tmp/application.properties
      register: envFile

    - name: create env files, copy only if the file doesn't exist 
      template: src="templates/env_template.yml" dest="/tmp/application.properties"
      when: envFile.stat.exists == False

    - name: say bye 
      debug: 
        msg: "BYE from Main program"

  handlers: 
    - include: handlers/included_handlers.yml
    - name: just a notify 
      debug: 
        msg: "inside main handler" 
    
